import sys
import numpy as np
import pyvista as pv
import argparse
import os

def parse_mesh(mesh_path):
    """Parses .mesh file to create a PyVista UnstructuredGrid of tetrahedra."""
    print(f"Reading mesh: {mesh_path}")
    with open(mesh_path, 'r') as f:
        lines = [line.strip() for line in f if line.strip() and not line.strip().startswith('#')]
    num_nodes, num_elems = int(lines[0]), int(lines[1])
    # Parse XYZ coordinates
    nodes = np.array([[float(x) for x in lines[i].split()] for i in range(2, 2 + num_nodes)])
    # Parse tetrahedral connectivity
    cells = []
    for i in range(2 + num_nodes, 2 + num_nodes + num_elems):
        parts = [int(x) for x in lines[i].split()]
        cells.append([4, parts[0]-1, parts[1]-1, parts[2]-1, parts[3]-1])
    return pv.UnstructuredGrid(np.hstack(cells), [pv.CellType.TETRA]*num_elems, nodes)

def parse_grid(grid_path):
    """Parses high-resolution .grid file generated by TIM-OS symmetry accumulator."""
    print(f"Reading grid data: {grid_path}")
    with open(grid_path, 'r') as f:
        lines = f.readlines()
    nr, ny, nt = 0, 0, 0
    start_idx = -1
    for i, line in enumerate(lines):
        if line.startswith('3 '):
            parts = line.split()
            nr, ny, nt = int(parts[1]), int(parts[2]), int(parts[3])
            start_idx = i + 1
            break
    data = np.zeros((nr, ny, nt))
    for i in range(nr * ny):
        parts = lines[start_idx + i].split()
        data[int(parts[0]), int(parts[1]), :] = [float(x) for x in parts[2:]]
    return data, nr, ny, nt

def main():
    parser = argparse.ArgumentParser(description="TIM-OS Visualization Tool v3.0")
    parser.add_argument("--mesh", required=True, help="Path to .mesh file")
    parser.add_argument("--data", required=True, help="Path to .dat result file")
    parser.add_argument("--grid", help="Path to .grid result file")
    parser.add_argument("--output", help="Output filename (.mp4 or .png)")
    parser.add_argument("--log", action="store_true", help="Logarithmic scale")
    parser.add_argument("--animate", action="store_true", help="Generate MP4 animation")
    parser.add_argument("--smooth", type=float, default=1.0, help="Gaussian smoothing sigma")
    parser.add_argument("--vmin", type=float, help="Manual min value (log if --log)")
    parser.add_argument("--vmax", type=float, help="Manual max value (log if --log)")
    parser.add_argument("--drange", type=float, help="Dynamic range in log units (e.g. 4.0)")
    parser.add_argument("--max-steps", type=int, help="Limit animation frames")
    parser.add_argument("--preview-frame", type=int, help="Frame to show in static/interactive preview")
    parser.add_argument("--interactive", action="store_true", help="Open visual tuner with sliders")
    args = parser.parse_args()

    # Load and Preprocess Grid Data
    if not args.grid:
        print("Error: Grid file required for high-res visualization.")
        return
    
    data, nr, ny, nt = parse_grid(args.grid)
    if args.max_steps and args.max_steps < nt: nt = args.max_steps
    
    # Apply Gaussian Smoothing to reduce Monte Carlo noise
    if args.smooth > 0:
        from scipy.ndimage import gaussian_filter
        print(f"Smoothing data (sigma={args.smooth})...")
        for t in range(nt): data[:, :, t] = gaussian_filter(data[:, :, t], sigma=args.smooth)

    # Parse Physical Dimensions from Grid Header
    rmax, ymax = 3.0, 5.0
    with open(args.grid, 'r') as f:
        for l in f.readlines()[:10]:
            if "Rmax=" in l:
                parts = l.replace("%","").strip().split()
                for p in parts:
                    if "Rmax=" in p: rmax = float(p.split('=')[1])
                    if "Ymax=" in p: ymax = float(p.split('=')[1])

    # Construct the visualization grid (ImageData)
    # We mirror the radial data (-R to R) to show a full axial cross-section
    mesh = pv.ImageData(dimensions=(2*nr, ny, 1), spacing=(rmax/nr, ymax/ny, 1))
    mesh.origin = (-rmax, 0, 0)
    
    def get_step_data(t):
        """Prepares a single frame of mirrored, optionally log-scaled grid data."""
        d = np.zeros((2*nr, ny))
        # Fold radial data across the center axis
        d[:nr, :] = np.flipud(data[:, :, t]); d[nr:, :] = data[:, :, t]
        # Return transposed for correct XY orientation in PyVista
        return np.log10(d.T + 1e-18) if args.log else d.T

    # Calculate Global Scaling (Fixed Scale for Animations)
    actual_max = -1e20
    for t in range(nt):
        m = np.nanmax(get_step_data(t))
        if m > actual_max: actual_max = m
    
    v_max = args.vmax if args.vmax is not None else actual_max
    v_min = args.vmin if args.vmin is not None else (v_max - (args.drange if args.drange else 3.0))
    current_frame = args.preview_frame if args.preview_frame is not None else nt // 4

    if args.interactive:
        # Interactive Visual Tuner: Allows real-time adjustment of Frame and Color Scale
        print("\n--- Visual Tuner Instructions ---")
        print("1. Use sliders to adjust Frame, VMin, and VMax.")
        print("2. Close the window to accept values and proceed to render.")
        
        plotter = pv.Plotter(title="TIM-OS Visual Tuner")
        mesh.point_data["Fluence"] = get_step_data(current_frame).flatten()
        actor = plotter.add_mesh(mesh, scalars="Fluence", cmap="jet", clim=[v_min, v_max])
        plotter.view_xy()

        # Callbacks for interactive sliders
        def update_frame(val):
            nonlocal current_frame
            current_frame = int(val)
            mesh.point_data["Fluence"] = get_step_data(current_frame).flatten()

        def update_vmin(val):
            nonlocal v_min
            v_min = val
            actor.mapper.scalar_range = (v_min, v_max)

        def update_vmax(val):
            nonlocal v_max
            v_max = val
            actor.mapper.scalar_range = (v_min, v_max)

        # Add GUI controls
        plotter.add_slider_widget(update_frame, [0, nt-1], value=current_frame, title="Frame", pointa=(0.05, 0.1), pointb=(0.35, 0.1))
        plotter.add_slider_widget(update_vmin, [v_min-5, v_max], value=v_min, title="VMin", pointa=(0.4, 0.1), pointb=(0.65, 0.1))
        plotter.add_slider_widget(update_vmax, [v_min, v_max+2], value=v_max, title="VMax", pointa=(0.7, 0.1), pointb=(0.95, 0.1))
        
        plotter.show()
        print(f"Accepted Range: {v_min:.2f} to {v_max:.2f} at frame {current_frame}")

    # Execution Phase: Animation or Static Screenshot
    if args.animate and nt > 1:
        plotter = pv.Plotter(off_screen=True if args.output else False)
        mesh.point_data["Fluence"] = get_step_data(0).flatten()
        actor = plotter.add_mesh(mesh, scalars="Fluence", cmap="jet", clim=[v_min, v_max])
        plotter.view_xy()
        
        video_path = args.output if args.output else "animation.mp4"
        plotter.open_movie(video_path)
        print(f"Generating animation to {video_path}...")
        for i in range(nt):
            mesh.point_data["Fluence"] = get_step_data(i).flatten()
            plotter.write_frame()
        plotter.close()
        print("Done.")
    elif args.output:
        plotter = pv.Plotter(off_screen=True)
        mesh.point_data["Fluence"] = get_step_data(current_frame).flatten()
        plotter.add_mesh(mesh, scalars="Fluence", cmap="jet", clim=[v_min, v_max])
        plotter.view_xy()
        plotter.screenshot(args.output)
        print(f"Saved screenshot to {args.output}")
    else:
        # Standard 2D View
        plotter = pv.Plotter()
        mesh.point_data["Fluence"] = get_step_data(current_frame).flatten()
        plotter.add_mesh(mesh, scalars="Fluence", cmap="jet", clim=[v_min, v_max])
        plotter.view_xy()
        plotter.show()

if __name__ == "__main__":
    main()
